# Import config which will be overwritten
imports:
    - { resource: ../../docs/config/config_prod.yml }

###############################################
##
##      Framework configuration
##
hathoora:
    translation:
        enabled: 1
        cache_service: @cache@
        cache_time: 86400
        dsn: default
        show_empty: true
        languages: [ en_US, fr_FR ]
        default_language: en_US
        debug:
            # GET, HEADER
            method: GET
            parameter: tkDebug


    # filter used in translation helper
    detokenizerFilters:
        - hathoora\admin\helper\translationFilter

    # cache configurations
    cache:
        pools:
            common: { driver: 'memcache', servers: [{host: "localhost", port: 11211}]}


###############################################
##
##      Services
##
services:
    #hathoora cache service
    cache_base:
        class: \hathoora\cache\cache
        calls:
            setContainer: [ @container@ ]
        type: static

    # factory service for cache
    cache:
        factory_service: @cache_base@
        factory_method: pool
        #will use hathoora.cache.pools.common
        factory_method_args: [ "common" ]