# configuration file for 'prod' environment
hathoora:
    logger:
        profiling: 1
        logging:
            enabled: 1
            level: DEBUG
        webprofiler:
            enabled: 1

    template:
          engine:
              name: Stuob

    database:
        default: mysql://dbuser:dbpassword@dbhost:3306/dbname
