# Define application or website that are being supported for prod environment
app:
    # admin site
    admin:
        pattern: '/admin(|/)'
        directory: sample

    # docs site
    docs:
        pattern: '/docs(|/)'
        directory: sample
        dispatcher:
            class: customDispatcher
            method: dispatch

    # Default site
    site:
        default: true