# Import config which will be overwritten
imports:
    - { resource: ../../docs/config/config_prod.yml }

###############################################
##
##      Framework configuration
##
hathoora:
    translation:
        enabled: 1
        debug: 1
        cache_service: @cache@
        cache_time: 86400
        dsn: default
        hide_empty_items: false
        languages: [ en_US, fr_FR ]

    database:
        default: mysql://dbuser:dbpassword@localhost:3306/dbname

    # cache configurations
    cache:
        debug: 1
        pools:
            common: { driver: 'memcache', servers: [{host: "localhost", port: 11211}]}


###############################################
##
##      Services
##
services:
    #hathoora cache service
    cache_base:
        class: \hathoora\cache\cache
        calls:
            setContainer: [ @container@ ]
        type: static

    # factory service for cache
    cache:
        factory_service: @cache_base@
        factory_method: pool
        #will use hathoora.cache.pools.common
        factory_method_args: [ "common" ]